### ISSUE TITLE
"FW Rand 1"

### ISSUE THREAD

**Issue by IntegratedQuantum** [finite-galaxy/finite-galaxy#25]
A mission which contains contradictions:
1. The mission name tells you to attack Rand in Zeta Aquilae
2. The mission description tells you attack the destination which is Sinter in Albireo
3. The log entry tells you Hamlet in Albaldah and Hopper in Kaus Australis want to join FW
4. The mission dialog tells you about Hamlet in Albaldah and Sinter in Albireo
5. The npcs you are supposed to fight are in Peacock
There is definitly something wrong!

**Comment by finite-galaxy** [comment]
Thank you for pointing this out; hopefully solved in 3fe24a736ffe058339009d6df163513f4e791b14.

**Comment by IntegratedQuantum** [comment]
There still is a problem:
The mission now tells you to occupy Sinter in Albeirio, but the republic fleet is in Ascella.

**Comment by puzzlecube** [comment]
I Just got to it and can confirm it is still a problem @finite-galaxy , I have pinpointed it too.
Change line 1772 from:
    system "Ascella"
to:
    system "Albireo"
That ought to put the fleet in the right place.

**Comment by finite-galaxy** [comment]
The real problem is that I'm still undecided as what to do eventually with this and subsequent missions. Rand is just three jumps away and shouldn't join the Free Worlds. Sinter is in the South and should join the Free Worlds; however, it's position is so isolated that it doesn't make sense for the Republic to send anything to occupy it. A Republic fleet in Ascella (four jumps from Earth) makes sense to prevent Free World fleets from taking that route. It's not perfect, just a placeholder until I think of something better.
